apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extension-apiserver-authentication-reader
rules:
  - apiGroups: [""]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update"]
