apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-operator-leases-access
subjects:
  - kind: ServiceAccount
    name: keda-operator
    namespace: keda
roleRef:
  kind: ClusterRole
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
